FROM python:3.9

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

ADD ./core /bytes32/core

WORKDIR /bytes32/indexer
ADD ./indexer .

RUN poetry config virtualenvs.create false && poetry install

CMD ["python", "bytes32_indexer/main.py"]
